---

- name: restart supervisor
  service: name=supervisor state=restarted

- name: stop supervisor
  service: name=supervisor state=stopped

- name: start supervisor
  service: name=supervisor state=started