"""add_course_id_to_user

Revision ID: e415e91c6c2f
Revises: 7e3d4d6e7e68
Create Date: 2016-07-31 15:39:30.217669

"""

# revision identifiers, used by Alembic.
revision = 'e415e91c6c2f'
down_revision = '7e3d4d6e7e68'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

fake_users = table(
    'users',
    column('course_id', sa.Unicode(32)),
    column('username', sa.Unicode(128))
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('course_id',
                  sa.Unicode(length=32),
                  nullable=False,
                  server_default=u'sea401d2'))
    op.alter_column('users', 'course_id', server_default=None)
    op.execute(
        fake_users.update().where(
            fake_users.c.username == op.inline_literal(u'cewing')
        ).values(
            {'course_id': op.inline_literal(u'all')}
        )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course_id')
    ### end Alembic commands ###
